name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.repository }}:latest
#          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ssh://dokku@${{ secrets.DOKKU_SERVER_ADDRESS }}/tdd-django
          ssh_private_key: ${{ secrets.DOKKU_SSH_KEY }}
          deploy_docker_image: ${{ github.repository }}:latest
#          deploy_docker_image: ${{ github.repository }}:${{ github.sha }}
