name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Production
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          git_remote_url: ${{ secrets.DOKKU_REMOTE_URL }}/tdd-django
